version: '3.8'

services:
  db:
    image: postgres:13
    container_name: contas_db
    environment:
      POSTGRES_DB: contas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:22-jdk
    container_name: contas_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run
    depends_on:
      - db

volumes:
  postgres_data: